version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  web: # name of the first service
    build: . # specify the directory of the Dockerfile
    ports:
      - "3000:3000"
    links:
      - elasticserver
      - scraper
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  scraper:
    build: ./scraper
    ports:
      - "3001:3001"
    links:
      - elasticserver
  elasticserver:
    build: ./elasticsearch
    ports:
      - "9199:9199"
    links:
      - elastic
volumes:
  esdata: